apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: mypvc2 
  containers:
  - name: myapp
    image: busybox:latest 
    volumeMounts:
      - mountPath: "/root/home"
        name: pvc 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh","-c"]
    args: ["mkdir hom; tail -f /dev/null"] 

