apiVersion: v1
kind: Pod
metadata:
  name: web-apl
  labels:
    name: web-apl
spec:
  containers:
  - name: web-apl
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 443
        protocol: TCP
    volumeMounts:
      - mountPath: /etc/cert
        name: cert-vm
  volumes:
    - name: cert-vm
      secret:
        secretName: www-cert

