apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: contents-vol
          readOnly: true
    - name: cloner
      image: gramman75/cloner:1.0
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env: 
        - name: CONTENTS_SOURCE_URL
          value: "https://github.com/gramman75/web-contents"
      volumeMounts:
        - mountPath: /data
          name: contents-vol

  volumes:
    - name: contents-vol
      emptyDir: {}