# 개발 담당용 SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: prod
---
#k8s 1.24 부터 SA를 만들면 Secret이 자동으로 생성되지 않음.
#명시적으로 생성
apiVersion: v1
kind: Secret
metadata:
  name: developer-token 
  namespace: prod 
  annotations:
    kubernetes.io/service-account.name : developer-sa
type: kubernetes.io/service-account-token	 
---
# 개발 담당용 SA와 ClusetRole의 view 매핑
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-crb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: view
subjects:
- kind: ServiceAccount
  namespace: prod
  name: developer-sa

---
# 개발 담당자용 Role생성.(ClusterRole view에 포함되므로 필수는 아님)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log","services"]
  verbs: ["get", "list","watch"]
- apiGroups: ["extensions","apps"]
  resources: ["pods", "pods/log","services"]
  verbs: ["get", "list","watch"]
---
# 개발 담당용 SA와 developer-role 매핑
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-role
subjects:
- kind: ServiceAccount
  namespace: prod
  name: developer-sa
- kind: ServiceAccount
  namespace: test 
  name: developer-sa


