apiVersion: v1
kind: ServiceAccocunt
metadata:
  name: sysop-sa
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysop-crb
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sysop-sa
  namespace: prod 
  apiGroup: rbac.authorization.k8s.io