apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: java 
          image: gramman75/java-server:2.0 #rollout을 하기 위해서 image를 만들고 버전을 변경하여 apply 
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"