apiVersion: v1
kind: Service
metadata:
  name: maria-svc
  labels:
    app: maria-sts
spec:
  selector:
    app: maria-sts
  ports:
  - port: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maria-sts
spec:
  selector:
    matchLabels:
      app: maria-sts
  serviceName: maria-svc 
  replicas: 2
  template:
    metadata:
      labels:
        app: maria-sts
    spec:
      containers:
      - name: maria-container
        image: mariadb:latest 
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: qwerty
        ports:
        - containerPort: 3306 
          name: mariadb 
        volumeMounts:
        - name: pvc 
          mountPath: /var/lib/mysql 
          subPath: data
        livenessProbe:
          exec:
            command: ["mysqladmin","-p$MARIADB_ROOT_PASSWORD","ping"]
          initialDelaySeconds: 80
          timeoutSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: pvc 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hostpath 
      resources:
        requests:
          storage: 100Mi
